name: Update dependencies

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Run npm audit fix
        run: npm audit fix --force || true
      - name: Check for changes
        id: git-status
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push changes
        if: steps.git-status.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -B chore/npm-audit-fix
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "chore: run npm audit fix"
          git push --force --set-upstream origin chore/npm-audit-fix
      - name: Create pull request
        if: steps.git-status.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "chore: update vulnerable dependencies" \
            --body "Automated npm audit fix" \
            --head chore/npm-audit-fix \
            --base ${{ github.event.repository.default_branch }}
